### ISSUE TITLE
IE 11 supported?

### ISSUE THREAD

**Issue by KiranMohan** [anywhichway/nano-memoize#10]
Is nano-memoize supported on IE11?

I am trying to use Nano-memoize in my web application which also uses Typescript and Webpack to transpile the code to ES5. However the webpage simply **fails to load in IE 11**. It works in Chrome.  

I have followed the following steps:

- `npm install nano-memoize`
- added `import 'nano-memoize/browser/nano-memoize'` to my source file.
- memoized a function like const memoizedFunc = nanomemoize(myFunc)

(the web application is based on create-react-app but the memoized function is not directly used in React components).

**Comment by anywhichway** [comment]
@KiranMohan I have not tried that combination of options. However, I just ran some quick tests. IE11 does not support Object.assign which is used by nano-memoize and comes through on a Babel ES5 transpile so is likely to come through on webpack also. There is a polyfill here https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign You might be able to configure webpack to pull something like this in.

**Comment by anywhichway** [comment]
@KiranMohan I just pushed v1.1.6 with a test for ie11. All unit tests pass so long as the polyfill for Object.assign is provided.

**Comment by KiranMohan** [comment]
@anywhichway 
Figured out the root cause of my issue. See details here https://stackoverflow.com/questions/57968410/webpack-how-to-transpile-code-in-node-modules

I think transpiling nano-memoize might help other users avoid this issue. 

And thank you for this awesome library. 👍

**Comment by anywhichway** [comment]
@KiranMohan Thanks for the compliment. I just pushed v1.1.7 to Github (but not to NPM yet). I re-worked it by hand so it is fully compatible with IE 11 in order to keep the size down and the speed up. Take a look and tell me what you think.

**Comment by anywhichway** [comment]
@KiranMohan I am closing this so there are not lingering open issues. Re-open if you have a concern.
