### ISSUE TITLE
Options hash

### ISSUE THREAD

**Issue by richardscarrott** [anywhichway/nano-memoize#16]
A lot of our functions accept options hashes, e.g.

```
const nanoMemoize = require("nano-memoize");
const fn = ({ foo, bar }) => { ... };
const mfn = nanoMemoize(fn);
const fib = new Fib();
mfn({ foo: 'foo', bar: fib }); // miss
mfn({ foo: 'foo', bar: fib }); // miss :(
```

I understand nano-memoize provides `options.seralizer` and `options.equals` but I'm not quite sure how to use them to get a hit on the second call?

**Comment by igalklebanov** [comment]
For single object arguments, when not providing a serializer, the lib defaults to using a weakmap.
Weakmaps compare keys by reference.

You're passing a different object reference in the calls you make to your memoized function.
So the internal weakmap does not have an entry for the object in the second call.

For single argument function such as yours, either:

1. Call your function as follows:    

```javascript
const obj = { foo: 'foo', bar: fib };
mfn(obj); // miss
mfn(obj); // hit
```

2. Provide a serializer function. 

If a serializer function is provided, and no equals function is provided, the lib will use the serializer function's returned value as a key in the cache (which is a plain object).

So the serializer must return values that can be keys in plain javascript objects - strings or numbers.

The most common is stringifying objects.
```javascript
obj => JSON.stringify(obj)
```
... or other string representations that suit you.

If your objects have unique identifier/s and your function only cares about the identity of the objects, I'd return just the identifier/s.

**Comment by richardscarrott** [comment]
Make sense, thanks for the info!

**Comment by anywhichway** [comment]
@igalklebanov thanks for jumping in with a response

**Comment by anywhichway** [comment]
@richardscarrott JSON.stringify is slow. Suggest you try to avoid it.

**Comment by richardscarrott** [comment]
@anywhichway yeah I've found it to be slow. Ultimately I'd like `fn({ a, b, c })` and `fn(a, b, c)` to be treated in the same way; i.e. I'd like `a`, `b` and `c` to be compared by identity without the performance cost of `JSON.stringify` under the hood. How does nano-memoize serialize `fn(a, b, c)` under the hood?

**Comment by anywhichway** [comment]
see lines 39 and 40 plus 76 through 80 using the parallel arrays k and v. k is a nested array caching arguments. v is a cache for results. every time a function is called the code looks through k to see if it can find a matching set of args, if it can, it uses the index of that arg set to retrieve the cached result from v.

it might actually be possible to do what you describe ... i will noodle on it.

Sent via the Samsung Galaxy S20 5G, an AT&T 5G smartphone

________________________________
