### ISSUE TITLE
Bug in vrgs function?

### ISSUE THREAD

**Issue by gregjacobs** [anywhichway/nano-memoize#17]
On line 25 (https://github.com/anywhichway/nano-memoize/blob/master/index.js#L25), the code reads:

```ts
return i>=0 && i<s.indexOf(")" || s.indexOf("arguments")>=0);
//                            ^-- missing end parenthesis?
```

The inner expression as it is currently written (`")" || s.indexOf("arguments")>=0`) will always evaluate to `")"`

**Comment by anywhichway** [comment]
@gregjacobs Thank you so much!

**Comment by gregjacobs** [comment]
Np! Hope you wrote a test for that guy? :)
