### ISSUE TITLE
Question: How to clear the cache?

### ISSUE THREAD

**Issue by guivr** [anywhichway/nano-memoize#5]
Hello!

First, this is really useful, thanks for creating it :)

I just have one question: how to clear the cache?

I'm using it like this: `const css = memoize(_css_, { serializer: hash })` but I'll need to clear all the cache at some point on the app. How to do this? Changing the hash?

Thanks!

**Comment by anywhichway** [comment]
`nanomemize` does not take `{serializer: has}` as an options, so not sure you are actually using `nanomemoize`. That being said, you should be able to use `css.clear()`.

**Comment by guivr** [comment]
Hey @anywhichway thanks for the reply.

I'm actually using `nano-memoize`, but `hash` is from the library (`hash-it`).
The `css.clear()` worked! PS: It is not in the documentation.

Thankss :)

**Comment by anywhichway** [comment]
@guivr Thanks ... added to docs.
