### ISSUE TITLE
Missing serializer causes `TypeError: p is not a function`

### ISSUE THREAD

**Issue by aaronmccall** [anywhichway/nano-memoize#6]
Version 1.1.1 removes the default serializer arg (`serializer = value => JSON.stringify(value)`).

This breaks the case where the single argument to the memoized function is itself a function:

```
> const memoize = require('nano-memoize')
undefined
> const memoized = memoize(fn => o => fn(o))
undefined
> const myFunc = memoized(o => console.log(o))
TypeError: p is not a function
    at Object.<anonymous> (/Users/aaronmccall/Projects/phytochrome-web-ui/node_modules/nano-memoize/index.js:35:118)
>
```

**Comment by anywhichway** [comment]
Will fix in the next 24 hours.

**Comment by anywhichway** [comment]
@aaronmccall Fixed, although not by re-introducing default arg. instead, do a type check for "function" in the code and branch. unit test added. thanks for finding the bug!
