### ISSUE TITLE
clearing cache with max age

### ISSUE THREAD

**Issue by darkship** [anywhichway/nano-memoize#63]
Hello,

I'm using your lib like this:
```
const memo = nanomemoize(fn, { maxAge: 7_200_000 })

memo()
...
memo.clear()
```

While calling `memo.clear()` clears the cache, the [setTimeout](https://github.com/anywhichway/nano-memoize/blob/ca71d163db33fc894584133d3dc942cfb404f382/src/index.js#L44C46-L44C46) is not cleared and the process hangs.

**Comment by anywhichway** [comment]
Thanks, I will look into it over the next couple of days.

________________________________
From: Thomas ***@***.***>
Sent: Thursday, November 16, 2023 8:59:23 AM
To: anywhichway/nano-memoize ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anywhichway/nano-memoize] clearing cache with max age (Issue #63)


Hello,

I'm using your lib like this:

const memo = nanomemoize(fn, { maxAge: 7_200_000 })

memo()
...
memo.clear()


While calling memo.clear() clears the cache, the setTimeout<https://github.com/anywhichway/nano-memoize/blob/ca71d163db33fc894584133d3dc942cfb404f382/src/index.js#L44C46-L44C46> is not cleared and the process hangs.

**Comment by anywhichway** [comment]
I added the timeout clear and published as 3.0.16. I did not write a unit test to check this (since I am currently out sailing). However, you could test. All existing unit tests pass.

**Comment by darkship** [comment]
Now I'm not sure about what is happening.
I'm using jest in my project and it breaks my tests:
```
    jest.useFakeTimers();

    const testFn = jest.fn();
    const maxAge = 10_000;
    const memo = memoize(testFn, { maxAge });

    memo(1); // first call
    jest.advanceTimersByTime(maxAge / 2);
    memo(1);
    expect(testFn).toHaveBeenCalledTimes(1);

    jest.advanceTimersByTime(maxAge * 2); //<- the max age should have been reached and the cache gone
    memo(1);
    expect(testFn).toHaveBeenCalledTimes(2); //<- it breaks here, the memoized function was never called a 2nd time
```

**Comment by darkship** [comment]
works
