### ISSUE TITLE
missing type definitions

### ISSUE THREAD

**Issue by darkship** [anywhichway/nano-memoize#64]
Hello,
[keys](https://github.com/anywhichway/nano-memoize/blob/ca71d163db33fc894584133d3dc942cfb404f382/src/index.js#L103) and [values](https://github.com/anywhichway/nano-memoize/blob/ca71d163db33fc894584133d3dc942cfb404f382/src/index.js#L104) are not defined in `index.d.ts`

**Comment by anywhichway** [comment]
The .ts file was created by another user. I am not a TS fan or expert. Any chance you could update?

________________________________
From: Thomas ***@***.***>
Sent: Thursday, November 16, 2023 9:05:00 AM
To: anywhichway/nano-memoize ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [anywhichway/nano-memoize] missing type definitions (Issue #64)


Hello,
keys<https://github.com/anywhichway/nano-memoize/blob/ca71d163db33fc894584133d3dc942cfb404f382/src/index.js#L103> and values<https://github.com/anywhichway/nano-memoize/blob/ca71d163db33fc894584133d3dc942cfb404f382/src/index.js#L104> are not defined in index.d.ts

**Comment by anywhichway** [comment]
Enhanced TypeScript types. Thanks @darkship.
