### ISSUE TITLE
TypeError: nanomemoize is not a function

### ISSUE THREAD

**Issue by IsraPerez98** [anywhichway/nano-memoize#70]
Hey, I'm having trouble using this library correctly. If I’m not mistaken, placing the following code in an index.js file should work:
`
const nanomemoize = require('nano-memoize');

function sum(a, b) {
  return a + b;
}

const memoized = nanomemoize(sum);
console.log(memoized(1, 2)); // 3
console.log(memoized(1, 2)); // pulled from cache
`

However, I’m encountering this error:

```
test-memoize/index.js:7
const memoized = nanomemoize(sum);
                 ^

TypeError: nanomemoize is not a function
```

When I run:
`
console.log(typeof nanomemoize);

console.log(nanomemoize);
`

It outputs:
`
object
{ nanomemoize: [Getter], default: [Getter] }
`

Using nanomemoize.default does work, but when I try to use it in a TypeScript environment, it throws a lot of errors in the IDE. Any guidance on how to resolve this would be much appreciated!

**Comment by anywhichway** [comment]
@IsraPerez98 Try using the code from the src directory with module import syntax rather than require. Let me know what happens. I generally do not use TypeScript.

**Comment by IsraPerez98** [comment]
Changed it to this:

```
import nanomemoize from 'nano-memoize';

console.log(typeof nanomemoize);

console.log(nanomemoize);
```

And i moved the index.js to src/

I get the following output:
```
node src/index.js
object
{ nanomemoize: [Getter], default: [Getter] }
````

If i try to memoize a function like this:
```
function sum(a, b) {
    return a + b;
}

const memoizedSum = nanomemoize(sum);
```

I still get the error, I could use nanomemoize.default or nanomemoize.nanomemoize, but I don't think this would be the ideal way of using the library.

**Comment by anywhichway** [comment]
@IsraPerez98 The src file obviously exports the right stuff: `export {nanomemoize,nanomemoize as default}` as does the dist version:

```
$parcel$export(module.exports, "nanomemoize", () => $4fa36e821943b400$export$22f15dd4e5be7e52);
$parcel$export(module.exports, "default", () => $4fa36e821943b400$export$22f15dd4e5be7e52);
```

The problem must be index.d.ts shown below. Since I do not use TypeScript and someone else wrote this a a courtesy, I have no idead what to change. Do you?

```
type Func = (...args: any[]) => any

declare module "nano-memoize" {
	interface BasicHelpers<T extends Func>
	{
		clear(): void;
		values(): ReturnType<T>[]
	}

	interface KeysHelpers<K>{
		keys(): K[]
	}

	export default function memoized<T extends Func, K = Parameters<T>>(
		fn: T,
		options?: {
			/**
			 * Only use the provided maxArgs for cache look-up, useful for ignoring final callback arguments
			 */
			maxArgs?: number;
			/**
			 * Number of milliseconds to cache a result, set to `Infinity` to never create timers or expire
			 */
			maxAge?: number;
			/**
			 * The serializer/key generator to use for single argument functions (optional, not recommended)
			 * must be able to serialize objects and functions, by default a WeakMap is used internally without serializing
			 */
			serializer?: (...args: Parameters<T>) => K;
			/**
			 * the equals function to use for multi-argument functions (optional, try to avoid) e.g. deepEquals for objects
			 */
			equals?: (...args: any[]) => boolean;
			/**
			 * Forces the use of multi-argument paradigm, auto set if function has a spread argument or uses `arguments` in its body.
			 */
			vargs?: boolean;
		}
	): T & BasicHelpers<T> & KeysHelpers<K>;
}
```

**Comment by anywhichway** [comment]
@IsraPerez98 submitted a pull request that closed this issue. Thanks @IsraPerez98!
